### PR TITLE
Lint everything + add lint check to Travis

### PR DESCRIPTION
**Pull request by mparent61**
Cleanup in preparation for upcoming refactor work (storage backend) 

@MichaelButkovic @benghaziboy @csinchok

### CODE REVIEW

**Comment by benghaziboy** [comment]
who is that last handle? not welcome

**Comment by benghaziboy** [comment]
LGTM, cam

**Comment by csinchok** [comment]
I actually think this code is perfect and requires no changes. It is the holy bible of code. An angel gave it to me on golden plates.

**Comment by mparent61** [comment]
The Master has returned! Praise be!

**Pull request merged**
