### PR TITLE
Add detail delete

### PR DESCRIPTION
**Pull request by mparent61**
@csinchok  this what you had in mind?

### CODE REVIEW

**Comment by csinchok** [comment]
Yes, this is great. Only one thing missing: we need to clear out the files on the filesystem, or else we're gonna be serving up some cached crops.

**Comment by mparent61** [comment]
via Image.clear_crops() ?

**Comment by mparent61** [comment]
Now flushes + deletes files via post_delete signal

**Comment by csinchok** [comment]
Awesome, this looks great.

**Pull request merged**
