### PR TITLE
Fix client only clear crops

### PR DESCRIPTION
**Pull request by mparent61**
Fixes a bug that does not flush all breakpoints. 

BETTY_CLIENT_ONLY_WIDTHS was a pre-2.0 workaround to add larger breakpoints without writing them to disk (due to pre-betty-2.0 storage limitations) that will be deprecated post-2.0. 

@MichaelButkovic @benghaziboy

### CODE REVIEW

**Comment by MichaelButkovic** [comment]
👍

**Comment by benghaziboy** [comment]
barring tests
👍

**Comment by mparent61** [comment]
Something broke with Travis testing environment, even old commits that previously passed are now failing with Python 2.7.
I'll keep investigating.

**Comment by mparent61** [comment]
Had to pin scipy==0.17.0, new 0.17.1 breaks betty tests

**Pull request merged**
